package de.rholambdapi.hypp.cli.render

import de.rholambdapi.hypp.HypDocument

object AsciiDocRenderer : Renderer {
    private val syntax = MarkupSyntax(
        boldOpen = "*",
        boldClose = "*",
        italicOpen = "_",
        italicClose = "_",
        underlineOpen = "[.underline]#",
        underlineClose = "#",
        link = { label, target -> "link:#$target[$label]" },
        // AsciiDoc's native admonition block: the `[NOTE]` attribute line plus an `====` example
        // block, which is what lets the admonition hold more than one line.
        popup = { label, content -> "*$label*\n\n[NOTE]\n====\n$content\n====\n" },
        stub = { label, description -> "*$label* _($description)_" },
        // An explicit `[#id]` block attribute sets that literal id on the following section (no
        // autogenerated prefix), matching `link:#id[]`'s href exactly.
        heading = { level, text, index -> "[#$index]\n" + "=".repeat(level) + " " + text },
        escape = { text ->
            text.replace("\\", "\\\\")
                .replace("*", "\\*")
                .replace("_", "\\_")
                .replace("#", "\\#")
                .replace("`", "\\`")
                .replace("+", "\\+")
                // Brackets, not just emphasis: `pass:[…]` is AsciiDoc's raw-passthrough macro, so an
                // entry named `pass:[<script>…</script>]` would otherwise reach asciidoctor's HTML
                // output as live markup. `\[` keeps the bracket literal and no macro or attribute
                // list can form. It also stops a `]` in a link label closing `link:#N[…]` early.
                .replace("[", "\\[")
                .replace("]", "\\]")
        }
    )

    override fun render(document: HypDocument): String = renderMarkup(document, syntax)
}
