package de.rholambdapi.hypp.cli.render

import de.rholambdapi.hypp.HypDocument

object AsciiDocRenderer : Renderer {
    private val syntax = MarkupSyntax(
        boldOpen = "*",
        boldClose = "*",
        italicOpen = "_",
        italicClose = "_",
        underlineOpen = "[.underline]#",
        underlineClose = "#",
        link = { label, target -> "link:#$target[$label]" },
        // An explicit `[#id]` block attribute sets that literal id on the following section (no
        // autogenerated prefix), matching `link:#id[]`'s href exactly.
        heading = { level, text, index -> "[#$index]\n" + "=".repeat(level) + " " + text },
        escape = { text ->
            text.replace("\\", "\\\\")
                .replace("*", "\\*")
                .replace("_", "\\_")
                .replace("#", "\\#")
                .replace("`", "\\`")
                .replace("+", "\\+")
        }
    )

    override fun render(document: HypDocument): String = renderMarkup(document, syntax)
}
